# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          # Semantic version range syntax or exact version of a Python version
          python-version: '3.7'
          # Optional - x64 or x86 architecture, defaults to x64
          architecture: 'x64'
        
      #install jq to parse json files
      - name: install jq
        run: sudo apt-get install jq
        
      - name: Download Openmodelica
        run: for deb in deb deb-src; do echo "$deb http://build.openmodelica.org/apt `lsb_release -cs` release"; done | sudo tee /etc/apt/sources.list.d/openmodelica.list
      
      - name: Import GPG Key
        run: wget -q http://build.openmodelica.org/apt/openmodelica.asc -O- | sudo apt-key add - 
        
      - name: Update Openmodelica
        run: sudo apt update
        
      - name: Install Openmodelica
        run: sudo apt install openmodelica
        
      - name: Install OMPython
        run: python -m pip install -U https://github.com/OpenModelica/OMPython/archive/master.zip
        
      - name: Run Pendulum Model
        run: python PendulumTest.py
        
        #The following action adds and commits the resulting file      
      - uses: EndBug/add-and-commit@v7 # You can change this to use a specific version
        with:
          # The arguments for the `git add` command (see the paragraph below for more info)
          # Default: '.'
          add: /home/runner/work/testing-CI/testing-CI/BouncingBall_res.mat

          # The name of the user that will be displayed as the author of the commit
          # Default: depends on the default_author input
          author_name: James Lewin

          # The email of the user that will be displayed as the author of the commit
          # Default: depends on the default_author input
          author_email: jblewin100@gmail.com

          # The local path to the directory where your repository is located. You should use actions/checkout first to set it up
          # Default: '.'
          cwd: '.'

          # Determines the way the action fills missing author name and email. Three options are available:
          # - github_actor -> UserName <UserName@users.noreply.github.com>
          # - user_info -> Your Display Name <your-actual@email.com>
          # - github_actions -> github-actions <email associated with the github logo>
          # Default: github_actor
          default_author: github_actor

          # The message for the commit
          # Default: 'Commit from GitHub Actions (name of the workflow)'
          message: 'result'

          # The flag used on the pull strategy. Use NO-PULL to avoid the action pulling at all.
          # Default: '--no-rebase'
          pull_strategy: 'NO-PULL'

          # Whether to push the commit and, if any, its tags to the repo. It can also be used to set the git push arguments (see the paragraph below for more info)
          # Default: true
          push: false

          # The arguments for the `git rm` command (see the paragraph below for more info)
          # Default: ''
          remove: '.'

          # Whether to use the --signoff option on `git commit` (only boolean values accepted*)
          # Default: false
          signoff: true

          # Arguments for the git tag command (the tag name always needs to be the first word not preceded by an hyphen)
          # Default: ''
          tag: 'v1.0.0 --force'
              
              

        

      
          
